# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\tmessaging\"@\n\x0fOutboundMessage\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\x1c\n\nMessageAck\x12\x0e\n\x06result\x18\x01 \x01(\t\"R\n\x0cStatusUpdate\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x1d\n\x0b\x43\x61llbackAck\x12\x0e\n\x06result\x18\x01 \x01(\t2\x98\x01\n\x10MessagingService\x12@\n\x0bSendMessage\x12\x1a.messaging.OutboundMessage\x1a\x15.messaging.MessageAck\x12\x42\n\x0fReceiveCallback\x12\x17.messaging.StatusUpdate\x1a\x16.messaging.CallbackAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OUTBOUNDMESSAGE']._serialized_start=28
  _globals['_OUTBOUNDMESSAGE']._serialized_end=92
  _globals['_MESSAGEACK']._serialized_start=94
  _globals['_MESSAGEACK']._serialized_end=122
  _globals['_STATUSUPDATE']._serialized_start=124
  _globals['_STATUSUPDATE']._serialized_end=206
  _globals['_CALLBACKACK']._serialized_start=208
  _globals['_CALLBACKACK']._serialized_end=237
  _globals['_MESSAGINGSERVICE']._serialized_start=240
  _globals['_MESSAGINGSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
